### ISSUE TITLE
Coding problem

### ISSUE THREAD

**Issue by zhangziyi123** [calvinmetcalf/shapefile-js#80]
There is a problem in Chinese；If the attribute value is Chinese, there will be a problem with the Chinese language

**Comment by calvinmetcalf** [comment]
checkout the new version I just published though see the note in the readme
about IE

**Comment by wxia5** [comment]
I' m having same issue here,Chinese character is not encoded correctly and I am using Chrome. What else steps are needed to display them correctly?Thanks.

**Comment by calvinmetcalf** [comment]
have you tried the nw version @wxia5 ?

**Comment by wxia5** [comment]
yes,I am using the gh-page branch and still no luck. However, I find this link works for me.
[link](https://github.com/gipong/shp2geojson.js)
It works fine for my data which is encoded in gb2312. Hope it helps a little bit.
Regards.

**Comment by K0den** [comment]
@calvinmetcalf I think the problem is here https://github.com/calvinmetcalf/shapefile-js/blob/gh-pages/lib/index.js#L93

parseDbf takes buffer and encoding. That line is giving it two buffers. (Or mostly buffer and undefined)

**Comment by K0den** [comment]
@fix in #95

**Comment by argoo83** [comment]
I am using the latest version of this library. 
And parseing a shp-file

`Observable.forkJoin([
        Observable.fromEvent(shpReader, 'loadend').first(),
        Observable.fromEvent(dbfReader, 'loadend').first()
      ]).subscribe(res => {
        let geoJson = shp.combine([shp.parseShp(shpReader.result), shp.parseDbf(dbfReader.result)])
        this.readGeoJsonInit(geoJson);

      });

      shpReader.readAsArrayBuffer(shpFile.shp);
      dbfReader.readAsArrayBuffer(shpFile.dbf);`

My attributevalues contains swedish chars and i can't manage to get them in right encoding. 
Any tips?

**Comment by calvinmetcalf** [comment]
`shp.parseDbf(dbfReader.result)` can take as a second argument the encoding, aka the contents of the `.cpg` file

**Comment by quyihang** [comment]
I got the same problem. The shp file created by ArcGIS doesn't contain cpg, while the Chinese characters are encoded by GBK. Then I use QGIS to edit the files, it works.
使用QGIS生成的shp可以在这个插件下正常使用。
